// import "./globals.css";
import { Footer } from "./components/Footer/Footer";
import { Header } from "./components/Header/Header";

export const metadata = {
  title: "Hello Next!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      {/* jako children renderuje się zawartość page.js */}
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
