// import "./globals.css";
import { Roboto } from "next/font/google";
import { Footer } from "./components/Footer/Footer";
import { Header } from "./components/Header/Header";

const roboto = Roboto({
  style: ["normal"],
  subsets: ["latin"],
  weight: "300",
});

export const metadata = {
  title: "Hello Next!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      {/* jako children renderuje się zawartość page.js */}
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
